# -*- mode: ruby -*-
# vi set ft=ruby

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "geerlingguy/centos7"
    config.vm.hostname = "nodejs.test"
    config.vm.network :private_network, ip: "192.168.55.55"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "forwarded_port", guest: 80, host: 8080
  
    config.vm.provider :virtualbox do |v|
        v.memory = 512
    end
  
    # Ansible provisioner.
    config.vm.provision :ansible do |ansible|
        ansible.playbook = "provisioning/playbook.yml"
    end
end
    
